Project1:对文件diabetes.csv中的数据进行处理

In [5]:
from pandas import *
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook
from scipy.stats import mode

#import os
#print(os.listdir("E:/input"))

In [6]:
################################读入diabetes.csv文件到diabetes################################### 
diabetes = pd.read_csv('/home/lidanyi/桌面/AI/diabetes.csv')
################################读入diabetes.csv文件到diabetes###################################

In [7]:
################################显示diabetes的前5行################################### 
diabetes.head(5)
################################显示diabetes的前5行###################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Check for Summary Statistics

In [8]:
################################显示diabetes的详细信息，包括样本数、均值、方差等等################################## 
diabetes.describe()   #describe的用法：求表格的详细信息，包括样本数、均值、方差等等
################################显示diabetes的详细信息，包括样本数、均值、方差等等##################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
################################显示diabetes中Outcome列中每种值出现的次数################################## 
diabetes["Outcome"].value_counts()
################################显示diabetes中Outcome列中每种值出现的次数##################################

0    500
1    268
Name: Outcome, dtype: int64

### Check missing values

In [10]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
################################显示diabetes中所有列的标题名################################## 
diabetes.columns   #栏
################################显示diabetes中所有列的标题名##################################

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [12]:
################################显示diabetes中所有列的值里面为0的个数################################## 
print((diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']] == 0).sum())
################################显示diabetes中所有列的值里面为0的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [13]:
################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']] = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']].replace(0, np.NaN)

################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [14]:
################################统计diabetes中所有列的值中为null的个数################################## 
diabetes.isnull().sum()
################################统计diabetes中所有列的值中为null的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

## Dealing with missing values

## A. Drop rows having NaN

In [15]:
print("Size before dropping NaN rows",diabetes.shape,"\n")

################################将diabetes中包含NaN的行删掉################################## 
nan_dropped = diabetes.dropna()

################################将diabetes中包含NaN的行删掉################################## 
print(nan_dropped.isnull().sum())
print("\nSize after dropping NaN rows",nan_dropped.shape)

Size before dropping NaN rows (768, 9)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Size after dropping NaN rows (336, 9)

### **Project2、数据分析的一系列问题**

In [16]:
vector = np.random.chisquare(1,500)
print(vector)
################################打印vector的均值################################## 
print("Mean",np.mean(vector))
################################打印vector的均值################################## 

print("SD",np.std(vector))
print("Range",max(vector)-min(vector))

[6.99200332e-01 2.80671996e+00 6.29847616e-04 1.13927790e-02
 1.93585821e+00 6.16317282e-01 1.93339573e-01 1.43985035e-01
 3.98246679e-01 1.14016960e+00 3.53654694e-01 4.61088419e-03
 5.03881032e-01 7.72406281e-02 1.30270937e+00 1.01609036e+00
 4.48320824e-01 1.48468569e+00 7.90184186e-01 9.84053334e-01
 3.69869027e+00 2.78705353e-02 2.32598172e+00 3.17628261e-01
 6.81800234e-02 5.44222266e-01 1.52818301e+00 2.11134595e-01
 2.26396822e-01 7.91350018e-02 4.87239280e-01 1.00647510e+00
 1.77373795e+00 1.49080139e-02 1.73803457e+00 3.89478363e+00
 8.82688432e-01 5.18695763e-01 1.32967450e+00 8.71742074e-01
 5.02123863e-02 3.02311622e+00 8.18304547e-01 2.69208673e+00
 4.77519470e-01 4.24131937e-02 1.39691038e+00 4.14348118e-03
 1.65283828e-02 5.80201823e+00 3.01787056e-01 2.31325543e-01
 2.48634159e-01 2.36923569e-01 2.81226612e-01 1.84599007e+00
 1.21139390e-01 2.86394281e-02 1.24538785e-01 2.45666229e-01
 7.65638154e-01 1.22610254e+00 3.56308303e-02 1.66887505e-01
 2.20001324e-01 3.00574240e-01 9.57983572e-01 1.20144515e-01
 8.58017752e-01 7.76978417e-03 1.00229038e+00 4.53446938e-01
 1.43925457e+00 3.42992922e-01 2.76023500e-01 5.78927352e+00
 1.91358638e-01 3.92965505e-01 3.49802119e-03 3.57922445e-01
 5.22503542e-01 5.96027899e-01 1.40373705e+00 2.64978869e-01
 3.79998941e+00 1.51529259e+00 1.67306438e-01 2.86732810e-01
 3.94457202e-01 1.02348421e+00 3.63308556e-01 3.09789517e+00
 1.18871330e-02 1.04474416e-02 1.57149829e-03 4.69241411e+00
 9.81764286e+00 7.36414967e-01 2.76053652e-02 1.08110394e+00
 1.44542021e-01 9.65719091e-02 6.43503652e-01 5.01601809e-01
 1.85483494e-02 1.43287880e+00 1.72018408e-01 4.88259033e+00
 5.17998837e-01 3.43636125e-02 4.49471200e-01 8.41452153e-01
 3.54026143e+00 1.32586375e-02 4.01880841e+00 1.24736613e+00
 3.46296851e+00 6.36576766e-02 1.49762179e-01 3.18027535e-01
 3.54229947e-01 2.21230863e-01 5.06503984e-01 2.83405036e+00
 3.77594104e-03 1.66438585e+00 1.32541442e+00 6.39175836e-02
 1.02461723e+00 5.38345142e+00 1.69396356e-01 4.99187825e-01
 2.89527315e-01 2.18233611e-01 2.44750206e-01 4.13287589e+00
 2.63058306e-01 5.00171640e+00 2.34083765e-01 1.38388092e-02
 3.08114962e-01 3.44554133e-01 2.32255173e-01 7.45064292e-01
 9.51390433e-01 6.53495844e-01 8.15559479e-02 2.17212156e+00
 3.16433636e+00 1.89309986e+00 1.02595926e-02 2.44146344e+00
 3.04550142e-01 3.37173927e+00 1.74539617e-01 3.05769424e-01
 4.32141777e-02 6.64410447e+00 4.62206168e-03 1.71000168e-01
 5.13364917e-02 9.59335407e-02 3.11683800e-02 1.90436412e-01
 9.89732114e-02 4.13905427e+00 2.72185619e-01 6.88788762e-01
 6.57291662e-03 2.70208934e+00 1.75091492e+00 6.11820833e-03
 6.31052560e-02 9.75893622e-01 4.91633285e-01 3.51002395e+00
 9.63487096e-01 4.94629383e+00 1.35487272e-03 3.10703451e+00
 9.01111486e-03 7.99917595e-01 5.05522825e+00 8.13181967e-01
 1.37269833e+00 4.38236227e-01 5.70700317e-01 1.40741577e-01
 8.07847401e-02 2.10588312e-01 7.30997934e-01 1.59277887e+00
 1.16228826e+00 1.39394536e-02 1.50772922e-02 1.37580144e+00
 7.94017800e-02 2.31357882e+00 9.94747896e-02 2.54252293e-01
 5.63955332e-01 6.49654190e-02 4.86840770e-01 1.51112244e+00
 1.19969601e-01 4.21403295e-02 2.31060787e-02 1.45447908e+00
 1.47020899e+00 6.00639699e-01 2.08479610e-03 3.90692417e-01
 2.13373677e+00 2.95104933e-01 1.83890221e+00 3.53275860e-01
 2.69588726e-01 8.00469489e-01 6.56137001e-01 7.59718438e-07
 5.68498956e-01 3.27175954e+00 6.01070770e-02 1.95843453e+00
 3.76982305e+00 1.10172038e-02 2.62311948e+00 1.54381991e-02
 2.34657017e+00 2.35091632e+00 7.80101995e-02 9.84553329e-02
 1.60783843e+00 1.29662655e+00 7.54485332e+00 1.91212133e+00
 3.25011796e+00 1.99875091e+00 2.76598645e-01 1.39755297e-05
 1.36005088e-01 1.84380422e-01 3.09546747e+00 4.20740284e-01
 6.09355885e-01 3.43480491e+00 2.94274202e+00 1.10450102e-01
 1.76975745e+00 4.87800470e-01 5.57710580e-01 2.74648308e-02
 4.55532572e-04 7.87645676e-01 4.07731150e-01 2.46661932e-02
 6.81204900e-02 2.40388053e-01 8.74649011e-03 9.07514436e-01
 4.83230575e-01 1.98985037e-01 5.90235026e-01 6.78110029e+00
 6.03293700e+00 4.28702257e-01 3.61496750e-02 7.13823259e-01
 1.56920452e-02 6.20470068e-02 5.05275660e-02 3.02611446e-03
 1.25147437e-01 3.31382173e-01 5.73873271e-01 1.15081655e+00
 7.28318087e-01 5.72020750e-03 7.33267616e-01 1.63334545e-01
 8.48400463e-01 1.19074997e-01 2.76528776e+00 1.50689883e+00
 4.11291492e-01 5.02927077e+00 1.13068223e-01 6.02656915e-01
 3.49588947e-01 8.81645771e-01 5.69820616e-02 1.67896384e-02
 4.39860762e-02 2.91264748e-02 2.74414153e-03 8.50615134e-01
 1.26300203e+00 5.94574510e-01 4.64172730e+00 2.54055103e+00
 8.64749522e-01 3.08685352e+00 2.89390396e+00 1.18290441e+00
 2.89083785e+00 4.61210040e-02 3.89658262e-01 3.93940942e-01
 2.75117672e+00 1.28367463e+00 1.05298016e-01 3.44717301e-01
 2.80608877e-01 2.03016777e+00 2.44485063e-02 2.39652092e-02
 3.88284473e+00 2.30758772e-02 5.85894477e-01 2.29219299e-01
 6.27097240e-02 1.60215332e-01 4.08866782e-02 9.99535693e-04
 6.27073536e-01 1.25922348e+00 3.25379665e+00 1.19260781e+00
 2.52429792e+00 4.70162361e-01 3.48138343e-01 8.03653935e-02
 3.65622272e+00 8.82407300e-03 1.02170729e+00 1.42448653e-01
 3.87388373e-03 1.39319510e+00 1.42022826e+00 1.74212673e+00
 1.20551314e-01 1.31899432e+00 1.97719830e-01 4.69971235e-01
 6.63539422e-01 9.63958083e-03 5.81886938e+00 1.44775103e+00
 2.46425346e-01 1.61412136e-01 2.09516133e-02 7.04739476e-01
 3.92372187e+00 1.45788100e+00 2.39519791e-01 2.59392641e+00
 5.39136225e-01 1.66013461e+00 3.94876643e-01 1.42907526e-01
 3.99793550e-02 1.39329546e+00 3.66382228e-02 1.24446432e+00
 1.00979976e+00 5.03158006e-03 2.62231261e-03 1.17540542e+00
 2.06820397e+00 2.11936047e-01 1.76103160e-01 6.87774867e-01
 8.43651620e-03 1.89739850e-01 8.35895715e-01 2.68337178e-01
 2.01529208e-02 3.85900885e+00 1.20270084e+00 2.15724526e-02
 1.03902638e+00 2.67482973e-01 4.80609389e+00 1.80026189e+00
 8.17371912e-01 6.51577600e-02 2.35401801e+00 2.08117324e-01
 1.23846806e+00 9.35026649e-06 3.27381930e-01 2.51844750e+00
 4.76311725e-01 1.68337737e-01 8.13027032e-01 1.48836497e-01
 1.33666673e-01 3.93623489e-01 3.43108977e+00 6.20477573e-01
 3.68419186e-01 1.98739227e-01 3.00317822e+00 4.82654539e-01
 1.48012626e-02 5.87515933e-01 4.05334211e-03 5.20599789e-01
 1.28213613e+00 5.64035147e+00 8.14036355e-05 2.95844910e-01
 2.06657912e-02 1.38199072e-02 9.25231851e-01 1.86676461e-02
 1.90526005e-02 5.21904447e-01 1.07969010e-01 1.00434005e+00
 8.81855925e-01 7.83242971e-01 9.31466728e-01 5.66614032e-03
 7.81074310e-01 7.56863671e-06 6.14785523e-02 1.96224196e+00
 2.17537927e-01 6.02986823e-03 9.35581967e-02 3.09373211e-01
 3.46246662e-01 4.14875366e-01 3.51942836e-01 4.40097693e-01
 3.21435129e+00 1.90213135e-03 4.01776573e+00 3.46027725e+00
 2.91160380e+00 2.82505799e+00 9.62587454e-01 6.88766612e-02
 7.75063944e-01 5.29733394e-01 2.65054745e-01 3.63007304e-01
 1.02423019e+00 5.18892949e+00 3.56530542e-01 1.48827120e+00
 9.13152842e-01 4.72701036e-02 9.45812242e-01 2.46026219e+00
 3.78671217e-01 2.52386548e+00 2.25392174e+00 2.07047432e+00
 1.37741170e+00 1.57094711e+00 4.87414039e+00 1.45106746e+00
 2.62871437e+00 7.77232119e-02 1.68094784e+00 4.22849373e-03
 1.22915477e-03 5.50318486e-02 9.50509393e-01 6.79589081e-01
 9.68464649e-01 1.36194584e-01 3.88571958e-01 2.29623872e+00
 2.65722052e+00 7.04718509e-02 3.03228326e-01 1.59848617e-01
 5.38671938e-01 9.00057075e-01 1.61503939e-02 1.91366708e+00
 4.60174619e-02 4.92194704e+00 2.54220100e-01 7.64731345e-01
 9.10526791e-01 3.90931868e-01 2.12115349e-01 4.03814773e-01
 3.03638562e-01 1.18514029e+00 1.38172079e+00 1.72032925e-01
 1.99029765e+00 3.68373762e+00 6.65975136e-01 4.47210838e-01]
Mean 1.0473131549313162
SD 1.3999961578829285
Range 9.817642098776302

### Reshape

In [17]:
vector.shape

(500,)

In [18]:
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector = vector.reshape(-1,1)
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector.shape
print(row_vector)

[[6.99200332e-01]
 [2.80671996e+00]
 [6.29847616e-04]
 [1.13927790e-02]
 [1.93585821e+00]
 [6.16317282e-01]
 [1.93339573e-01]
 [1.43985035e-01]
 [3.98246679e-01]
 [1.14016960e+00]
 [3.53654694e-01]
 [4.61088419e-03]
 [5.03881032e-01]
 [7.72406281e-02]
 [1.30270937e+00]
 [1.01609036e+00]
 [4.48320824e-01]
 [1.48468569e+00]
 [7.90184186e-01]
 [9.84053334e-01]
 [3.69869027e+00]
 [2.78705353e-02]
 [2.32598172e+00]
 [3.17628261e-01]
 [6.81800234e-02]
 [5.44222266e-01]
 [1.52818301e+00]
 [2.11134595e-01]
 [2.26396822e-01]
 [7.91350018e-02]
 [4.87239280e-01]
 [1.00647510e+00]
 [1.77373795e+00]
 [1.49080139e-02]
 [1.73803457e+00]
 [3.89478363e+00]
 [8.82688432e-01]
 [5.18695763e-01]
 [1.32967450e+00]
 [8.71742074e-01]
 [5.02123863e-02]
 [3.02311622e+00]
 [8.18304547e-01]
 [2.69208673e+00]
 [4.77519470e-01]
 [4.24131937e-02]
 [1.39691038e+00]
 [4.14348118e-03]
 [1.65283828e-02]
 [5.80201823e+00]
 [3.01787056e-01]
 [2.31325543e-01]
 [2.48634159e-01]
 [2.36923569e-01]
 [2.81226612e-01]
 [1.84599007e+00]
 [1.21139390e-01]
 [2.86394281e-02]
 [1.24538785e-01]
 [2.45666229e-01]
 [7.65638154e-01]
 [1.22610254e+00]
 [3.56308303e-02]
 [1.66887505e-01]
 [2.20001324e-01]
 [3.00574240e-01]
 [9.57983572e-01]
 [1.20144515e-01]
 [8.58017752e-01]
 [7.76978417e-03]
 [1.00229038e+00]
 [4.53446938e-01]
 [1.43925457e+00]
 [3.42992922e-01]
 [2.76023500e-01]
 [5.78927352e+00]
 [1.91358638e-01]
 [3.92965505e-01]
 [3.49802119e-03]
 [3.57922445e-01]
 [5.22503542e-01]
 [5.96027899e-01]
 [1.40373705e+00]
 [2.64978869e-01]
 [3.79998941e+00]
 [1.51529259e+00]
 [1.67306438e-01]
 [2.86732810e-01]
 [3.94457202e-01]
 [1.02348421e+00]
 [3.63308556e-01]
 [3.09789517e+00]
 [1.18871330e-02]
 [1.04474416e-02]
 [1.57149829e-03]
 [4.69241411e+00]
 [9.81764286e+00]
 [7.36414967e-01]
 [2.76053652e-02]
 [1.08110394e+00]
 [1.44542021e-01]
 [9.65719091e-02]
 [6.43503652e-01]
 [5.01601809e-01]
 [1.85483494e-02]
 [1.43287880e+00]
 [1.72018408e-01]
 [4.88259033e+00]
 [5.17998837e-01]
 [3.43636125e-02]
 [4.49471200e-01]
 [8.41452153e-01]
 [3.54026143e+00]
 [1.32586375e-02]
 [4.01880841e+00]
 [1.24736613e+00]
 [3.46296851e+00]
 [6.36576766e-02]
 [1.49762179e-01]
 [3.18027535e-01]
 [3.54229947e-01]
 [2.21230863e-01]
 [5.06503984e-01]
 [2.83405036e+00]
 [3.77594104e-03]
 [1.66438585e+00]
 [1.32541442e+00]
 [6.39175836e-02]
 [1.02461723e+00]
 [5.38345142e+00]
 [1.69396356e-01]
 [4.99187825e-01]
 [2.89527315e-01]
 [2.18233611e-01]
 [2.44750206e-01]
 [4.13287589e+00]
 [2.63058306e-01]
 [5.00171640e+00]
 [2.34083765e-01]
 [1.38388092e-02]
 [3.08114962e-01]
 [3.44554133e-01]
 [2.32255173e-01]
 [7.45064292e-01]
 [9.51390433e-01]
 [6.53495844e-01]
 [8.15559479e-02]
 [2.17212156e+00]
 [3.16433636e+00]
 [1.89309986e+00]
 [1.02595926e-02]
 [2.44146344e+00]
 [3.04550142e-01]
 [3.37173927e+00]
 [1.74539617e-01]
 [3.05769424e-01]
 [4.32141777e-02]
 [6.64410447e+00]
 [4.62206168e-03]
 [1.71000168e-01]
 [5.13364917e-02]
 [9.59335407e-02]
 [3.11683800e-02]
 [1.90436412e-01]
 [9.89732114e-02]
 [4.13905427e+00]
 [2.72185619e-01]
 [6.88788762e-01]
 [6.57291662e-03]
 [2.70208934e+00]
 [1.75091492e+00]
 [6.11820833e-03]
 [6.31052560e-02]
 [9.75893622e-01]
 [4.91633285e-01]
 [3.51002395e+00]
 [9.63487096e-01]
 [4.94629383e+00]
 [1.35487272e-03]
 [3.10703451e+00]
 [9.01111486e-03]
 [7.99917595e-01]
 [5.05522825e+00]
 [8.13181967e-01]
 [1.37269833e+00]
 [4.38236227e-01]
 [5.70700317e-01]
 [1.40741577e-01]
 [8.07847401e-02]
 [2.10588312e-01]
 [7.30997934e-01]
 [1.59277887e+00]
 [1.16228826e+00]
 [1.39394536e-02]
 [1.50772922e-02]
 [1.37580144e+00]
 [7.94017800e-02]
 [2.31357882e+00]
 [9.94747896e-02]
 [2.54252293e-01]
 [5.63955332e-01]
 [6.49654190e-02]
 [4.86840770e-01]
 [1.51112244e+00]
 [1.19969601e-01]
 [4.21403295e-02]
 [2.31060787e-02]
 [1.45447908e+00]
 [1.47020899e+00]
 [6.00639699e-01]
 [2.08479610e-03]
 [3.90692417e-01]
 [2.13373677e+00]
 [2.95104933e-01]
 [1.83890221e+00]
 [3.53275860e-01]
 [2.69588726e-01]
 [8.00469489e-01]
 [6.56137001e-01]
 [7.59718438e-07]
 [5.68498956e-01]
 [3.27175954e+00]
 [6.01070770e-02]
 [1.95843453e+00]
 [3.76982305e+00]
 [1.10172038e-02]
 [2.62311948e+00]
 [1.54381991e-02]
 [2.34657017e+00]
 [2.35091632e+00]
 [7.80101995e-02]
 [9.84553329e-02]
 [1.60783843e+00]
 [1.29662655e+00]
 [7.54485332e+00]
 [1.91212133e+00]
 [3.25011796e+00]
 [1.99875091e+00]
 [2.76598645e-01]
 [1.39755297e-05]
 [1.36005088e-01]
 [1.84380422e-01]
 [3.09546747e+00]
 [4.20740284e-01]
 [6.09355885e-01]
 [3.43480491e+00]
 [2.94274202e+00]
 [1.10450102e-01]
 [1.76975745e+00]
 [4.87800470e-01]
 [5.57710580e-01]
 [2.74648308e-02]
 [4.55532572e-04]
 [7.87645676e-01]
 [4.07731150e-01]
 [2.46661932e-02]
 [6.81204900e-02]
 [2.40388053e-01]
 [8.74649011e-03]
 [9.07514436e-01]
 [4.83230575e-01]
 [1.98985037e-01]
 [5.90235026e-01]
 [6.78110029e+00]
 [6.03293700e+00]
 [4.28702257e-01]
 [3.61496750e-02]
 [7.13823259e-01]
 [1.56920452e-02]
 [6.20470068e-02]
 [5.05275660e-02]
 [3.02611446e-03]
 [1.25147437e-01]
 [3.31382173e-01]
 [5.73873271e-01]
 [1.15081655e+00]
 [7.28318087e-01]
 [5.72020750e-03]
 [7.33267616e-01]
 [1.63334545e-01]
 [8.48400463e-01]
 [1.19074997e-01]
 [2.76528776e+00]
 [1.50689883e+00]
 [4.11291492e-01]
 [5.02927077e+00]
 [1.13068223e-01]
 [6.02656915e-01]
 [3.49588947e-01]
 [8.81645771e-01]
 [5.69820616e-02]
 [1.67896384e-02]
 [4.39860762e-02]
 [2.91264748e-02]
 [2.74414153e-03]
 [8.50615134e-01]
 [1.26300203e+00]
 [5.94574510e-01]
 [4.64172730e+00]
 [2.54055103e+00]
 [8.64749522e-01]
 [3.08685352e+00]
 [2.89390396e+00]
 [1.18290441e+00]
 [2.89083785e+00]
 [4.61210040e-02]
 [3.89658262e-01]
 [3.93940942e-01]
 [2.75117672e+00]
 [1.28367463e+00]
 [1.05298016e-01]
 [3.44717301e-01]
 [2.80608877e-01]
 [2.03016777e+00]
 [2.44485063e-02]
 [2.39652092e-02]
 [3.88284473e+00]
 [2.30758772e-02]
 [5.85894477e-01]
 [2.29219299e-01]
 [6.27097240e-02]
 [1.60215332e-01]
 [4.08866782e-02]
 [9.99535693e-04]
 [6.27073536e-01]
 [1.25922348e+00]
 [3.25379665e+00]
 [1.19260781e+00]
 [2.52429792e+00]
 [4.70162361e-01]
 [3.48138343e-01]
 [8.03653935e-02]
 [3.65622272e+00]
 [8.82407300e-03]
 [1.02170729e+00]
 [1.42448653e-01]
 [3.87388373e-03]
 [1.39319510e+00]
 [1.42022826e+00]
 [1.74212673e+00]
 [1.20551314e-01]
 [1.31899432e+00]
 [1.97719830e-01]
 [4.69971235e-01]
 [6.63539422e-01]
 [9.63958083e-03]
 [5.81886938e+00]
 [1.44775103e+00]
 [2.46425346e-01]
 [1.61412136e-01]
 [2.09516133e-02]
 [7.04739476e-01]
 [3.92372187e+00]
 [1.45788100e+00]
 [2.39519791e-01]
 [2.59392641e+00]
 [5.39136225e-01]
 [1.66013461e+00]
 [3.94876643e-01]
 [1.42907526e-01]
 [3.99793550e-02]
 [1.39329546e+00]
 [3.66382228e-02]
 [1.24446432e+00]
 [1.00979976e+00]
 [5.03158006e-03]
 [2.62231261e-03]
 [1.17540542e+00]
 [2.06820397e+00]
 [2.11936047e-01]
 [1.76103160e-01]
 [6.87774867e-01]
 [8.43651620e-03]
 [1.89739850e-01]
 [8.35895715e-01]
 [2.68337178e-01]
 [2.01529208e-02]
 [3.85900885e+00]
 [1.20270084e+00]
 [2.15724526e-02]
 [1.03902638e+00]
 [2.67482973e-01]
 [4.80609389e+00]
 [1.80026189e+00]
 [8.17371912e-01]
 [6.51577600e-02]
 [2.35401801e+00]
 [2.08117324e-01]
 [1.23846806e+00]
 [9.35026649e-06]
 [3.27381930e-01]
 [2.51844750e+00]
 [4.76311725e-01]
 [1.68337737e-01]
 [8.13027032e-01]
 [1.48836497e-01]
 [1.33666673e-01]
 [3.93623489e-01]
 [3.43108977e+00]
 [6.20477573e-01]
 [3.68419186e-01]
 [1.98739227e-01]
 [3.00317822e+00]
 [4.82654539e-01]
 [1.48012626e-02]
 [5.87515933e-01]
 [4.05334211e-03]
 [5.20599789e-01]
 [1.28213613e+00]
 [5.64035147e+00]
 [8.14036355e-05]
 [2.95844910e-01]
 [2.06657912e-02]
 [1.38199072e-02]
 [9.25231851e-01]
 [1.86676461e-02]
 [1.90526005e-02]
 [5.21904447e-01]
 [1.07969010e-01]
 [1.00434005e+00]
 [8.81855925e-01]
 [7.83242971e-01]
 [9.31466728e-01]
 [5.66614032e-03]
 [7.81074310e-01]
 [7.56863671e-06]
 [6.14785523e-02]
 [1.96224196e+00]
 [2.17537927e-01]
 [6.02986823e-03]
 [9.35581967e-02]
 [3.09373211e-01]
 [3.46246662e-01]
 [4.14875366e-01]
 [3.51942836e-01]
 [4.40097693e-01]
 [3.21435129e+00]
 [1.90213135e-03]
 [4.01776573e+00]
 [3.46027725e+00]
 [2.91160380e+00]
 [2.82505799e+00]
 [9.62587454e-01]
 [6.88766612e-02]
 [7.75063944e-01]
 [5.29733394e-01]
 [2.65054745e-01]
 [3.63007304e-01]
 [1.02423019e+00]
 [5.18892949e+00]
 [3.56530542e-01]
 [1.48827120e+00]
 [9.13152842e-01]
 [4.72701036e-02]
 [9.45812242e-01]
 [2.46026219e+00]
 [3.78671217e-01]
 [2.52386548e+00]
 [2.25392174e+00]
 [2.07047432e+00]
 [1.37741170e+00]
 [1.57094711e+00]
 [4.87414039e+00]
 [1.45106746e+00]
 [2.62871437e+00]
 [7.77232119e-02]
 [1.68094784e+00]
 [4.22849373e-03]
 [1.22915477e-03]
 [5.50318486e-02]
 [9.50509393e-01]
 [6.79589081e-01]
 [9.68464649e-01]
 [1.36194584e-01]
 [3.88571958e-01]
 [2.29623872e+00]
 [2.65722052e+00]
 [7.04718509e-02]
 [3.03228326e-01]
 [1.59848617e-01]
 [5.38671938e-01]
 [9.00057075e-01]
 [1.61503939e-02]
 [1.91366708e+00]
 [4.60174619e-02]
 [4.92194704e+00]
 [2.54220100e-01]
 [7.64731345e-01]
 [9.10526791e-01]
 [3.90931868e-01]
 [2.12115349e-01]
 [4.03814773e-01]
 [3.03638562e-01]
 [1.18514029e+00]
 [1.38172079e+00]
 [1.72032925e-01]
 [1.99029765e+00]
 [3.68373762e+00]
 [6.65975136e-01]
 [4.47210838e-01]]

In [19]:
col_vector = vector.reshape(1,-1)
col_vector.shape

(1, 500)

In [20]:
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix = vector.reshape(10,50)
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix.shape
print(matrix)

[[6.99200332e-01 2.80671996e+00 6.29847616e-04 1.13927790e-02
  1.93585821e+00 6.16317282e-01 1.93339573e-01 1.43985035e-01
  3.98246679e-01 1.14016960e+00 3.53654694e-01 4.61088419e-03
  5.03881032e-01 7.72406281e-02 1.30270937e+00 1.01609036e+00
  4.48320824e-01 1.48468569e+00 7.90184186e-01 9.84053334e-01
  3.69869027e+00 2.78705353e-02 2.32598172e+00 3.17628261e-01
  6.81800234e-02 5.44222266e-01 1.52818301e+00 2.11134595e-01
  2.26396822e-01 7.91350018e-02 4.87239280e-01 1.00647510e+00
  1.77373795e+00 1.49080139e-02 1.73803457e+00 3.89478363e+00
  8.82688432e-01 5.18695763e-01 1.32967450e+00 8.71742074e-01
  5.02123863e-02 3.02311622e+00 8.18304547e-01 2.69208673e+00
  4.77519470e-01 4.24131937e-02 1.39691038e+00 4.14348118e-03
  1.65283828e-02 5.80201823e+00]
 [3.01787056e-01 2.31325543e-01 2.48634159e-01 2.36923569e-01
  2.81226612e-01 1.84599007e+00 1.21139390e-01 2.86394281e-02
  1.24538785e-01 2.45666229e-01 7.65638154e-01 1.22610254e+00
  3.56308303e-02 1.66887505e-01 2.20001324e-01 3.00574240e-01
  9.57983572e-01 1.20144515e-01 8.58017752e-01 7.76978417e-03
  1.00229038e+00 4.53446938e-01 1.43925457e+00 3.42992922e-01
  2.76023500e-01 5.78927352e+00 1.91358638e-01 3.92965505e-01
  3.49802119e-03 3.57922445e-01 5.22503542e-01 5.96027899e-01
  1.40373705e+00 2.64978869e-01 3.79998941e+00 1.51529259e+00
  1.67306438e-01 2.86732810e-01 3.94457202e-01 1.02348421e+00
  3.63308556e-01 3.09789517e+00 1.18871330e-02 1.04474416e-02
  1.57149829e-03 4.69241411e+00 9.81764286e+00 7.36414967e-01
  2.76053652e-02 1.08110394e+00]
 [1.44542021e-01 9.65719091e-02 6.43503652e-01 5.01601809e-01
  1.85483494e-02 1.43287880e+00 1.72018408e-01 4.88259033e+00
  5.17998837e-01 3.43636125e-02 4.49471200e-01 8.41452153e-01
  3.54026143e+00 1.32586375e-02 4.01880841e+00 1.24736613e+00
  3.46296851e+00 6.36576766e-02 1.49762179e-01 3.18027535e-01
  3.54229947e-01 2.21230863e-01 5.06503984e-01 2.83405036e+00
  3.77594104e-03 1.66438585e+00 1.32541442e+00 6.39175836e-02
  1.02461723e+00 5.38345142e+00 1.69396356e-01 4.99187825e-01
  2.89527315e-01 2.18233611e-01 2.44750206e-01 4.13287589e+00
  2.63058306e-01 5.00171640e+00 2.34083765e-01 1.38388092e-02
  3.08114962e-01 3.44554133e-01 2.32255173e-01 7.45064292e-01
  9.51390433e-01 6.53495844e-01 8.15559479e-02 2.17212156e+00
  3.16433636e+00 1.89309986e+00]
 [1.02595926e-02 2.44146344e+00 3.04550142e-01 3.37173927e+00
  1.74539617e-01 3.05769424e-01 4.32141777e-02 6.64410447e+00
  4.62206168e-03 1.71000168e-01 5.13364917e-02 9.59335407e-02
  3.11683800e-02 1.90436412e-01 9.89732114e-02 4.13905427e+00
  2.72185619e-01 6.88788762e-01 6.57291662e-03 2.70208934e+00
  1.75091492e+00 6.11820833e-03 6.31052560e-02 9.75893622e-01
  4.91633285e-01 3.51002395e+00 9.63487096e-01 4.94629383e+00
  1.35487272e-03 3.10703451e+00 9.01111486e-03 7.99917595e-01
  5.05522825e+00 8.13181967e-01 1.37269833e+00 4.38236227e-01
  5.70700317e-01 1.40741577e-01 8.07847401e-02 2.10588312e-01
  7.30997934e-01 1.59277887e+00 1.16228826e+00 1.39394536e-02
  1.50772922e-02 1.37580144e+00 7.94017800e-02 2.31357882e+00
  9.94747896e-02 2.54252293e-01]
 [5.63955332e-01 6.49654190e-02 4.86840770e-01 1.51112244e+00
  1.19969601e-01 4.21403295e-02 2.31060787e-02 1.45447908e+00
  1.47020899e+00 6.00639699e-01 2.08479610e-03 3.90692417e-01
  2.13373677e+00 2.95104933e-01 1.83890221e+00 3.53275860e-01
  2.69588726e-01 8.00469489e-01 6.56137001e-01 7.59718438e-07
  5.68498956e-01 3.27175954e+00 6.01070770e-02 1.95843453e+00
  3.76982305e+00 1.10172038e-02 2.62311948e+00 1.54381991e-02
  2.34657017e+00 2.35091632e+00 7.80101995e-02 9.84553329e-02
  1.60783843e+00 1.29662655e+00 7.54485332e+00 1.91212133e+00
  3.25011796e+00 1.99875091e+00 2.76598645e-01 1.39755297e-05
  1.36005088e-01 1.84380422e-01 3.09546747e+00 4.20740284e-01
  6.09355885e-01 3.43480491e+00 2.94274202e+00 1.10450102e-01
  1.76975745e+00 4.87800470e-01]
 [5.57710580e-01 2.74648308e-02 4.55532572e-04 7.87645676e-01
  4.07731150e-01 2.46661932e-02 6.81204900e-02 2.40388053e-01
  8.74649011e-03 9.07514436e-01 4.83230575e-01 1.98985037e-01
  5.90235026e-01 6.78110029e+00 6.03293700e+00 4.28702257e-01
  3.61496750e-02 7.13823259e-01 1.56920452e-02 6.20470068e-02
  5.05275660e-02 3.02611446e-03 1.25147437e-01 3.31382173e-01
  5.73873271e-01 1.15081655e+00 7.28318087e-01 5.72020750e-03
  7.33267616e-01 1.63334545e-01 8.48400463e-01 1.19074997e-01
  2.76528776e+00 1.50689883e+00 4.11291492e-01 5.02927077e+00
  1.13068223e-01 6.02656915e-01 3.49588947e-01 8.81645771e-01
  5.69820616e-02 1.67896384e-02 4.39860762e-02 2.91264748e-02
  2.74414153e-03 8.50615134e-01 1.26300203e+00 5.94574510e-01
  4.64172730e+00 2.54055103e+00]
 [8.64749522e-01 3.08685352e+00 2.89390396e+00 1.18290441e+00
  2.89083785e+00 4.61210040e-02 3.89658262e-01 3.93940942e-01
  2.75117672e+00 1.28367463e+00 1.05298016e-01 3.44717301e-01
  2.80608877e-01 2.03016777e+00 2.44485063e-02 2.39652092e-02
  3.88284473e+00 2.30758772e-02 5.85894477e-01 2.29219299e-01
  6.27097240e-02 1.60215332e-01 4.08866782e-02 9.99535693e-04
  6.27073536e-01 1.25922348e+00 3.25379665e+00 1.19260781e+00
  2.52429792e+00 4.70162361e-01 3.48138343e-01 8.03653935e-02
  3.65622272e+00 8.82407300e-03 1.02170729e+00 1.42448653e-01
  3.87388373e-03 1.39319510e+00 1.42022826e+00 1.74212673e+00
  1.20551314e-01 1.31899432e+00 1.97719830e-01 4.69971235e-01
  6.63539422e-01 9.63958083e-03 5.81886938e+00 1.44775103e+00
  2.46425346e-01 1.61412136e-01]
 [2.09516133e-02 7.04739476e-01 3.92372187e+00 1.45788100e+00
  2.39519791e-01 2.59392641e+00 5.39136225e-01 1.66013461e+00
  3.94876643e-01 1.42907526e-01 3.99793550e-02 1.39329546e+00
  3.66382228e-02 1.24446432e+00 1.00979976e+00 5.03158006e-03
  2.62231261e-03 1.17540542e+00 2.06820397e+00 2.11936047e-01
  1.76103160e-01 6.87774867e-01 8.43651620e-03 1.89739850e-01
  8.35895715e-01 2.68337178e-01 2.01529208e-02 3.85900885e+00
  1.20270084e+00 2.15724526e-02 1.03902638e+00 2.67482973e-01
  4.80609389e+00 1.80026189e+00 8.17371912e-01 6.51577600e-02
  2.35401801e+00 2.08117324e-01 1.23846806e+00 9.35026649e-06
  3.27381930e-01 2.51844750e+00 4.76311725e-01 1.68337737e-01
  8.13027032e-01 1.48836497e-01 1.33666673e-01 3.93623489e-01
  3.43108977e+00 6.20477573e-01]
 [3.68419186e-01 1.98739227e-01 3.00317822e+00 4.82654539e-01
  1.48012626e-02 5.87515933e-01 4.05334211e-03 5.20599789e-01
  1.28213613e+00 5.64035147e+00 8.14036355e-05 2.95844910e-01
  2.06657912e-02 1.38199072e-02 9.25231851e-01 1.86676461e-02
  1.90526005e-02 5.21904447e-01 1.07969010e-01 1.00434005e+00
  8.81855925e-01 7.83242971e-01 9.31466728e-01 5.66614032e-03
  7.81074310e-01 7.56863671e-06 6.14785523e-02 1.96224196e+00
  2.17537927e-01 6.02986823e-03 9.35581967e-02 3.09373211e-01
  3.46246662e-01 4.14875366e-01 3.51942836e-01 4.40097693e-01
  3.21435129e+00 1.90213135e-03 4.01776573e+00 3.46027725e+00
  2.91160380e+00 2.82505799e+00 9.62587454e-01 6.88766612e-02
  7.75063944e-01 5.29733394e-01 2.65054745e-01 3.63007304e-01
  1.02423019e+00 5.18892949e+00]
 [3.56530542e-01 1.48827120e+00 9.13152842e-01 4.72701036e-02
  9.45812242e-01 2.46026219e+00 3.78671217e-01 2.52386548e+00
  2.25392174e+00 2.07047432e+00 1.37741170e+00 1.57094711e+00
  4.87414039e+00 1.45106746e+00 2.62871437e+00 7.77232119e-02
  1.68094784e+00 4.22849373e-03 1.22915477e-03 5.50318486e-02
  9.50509393e-01 6.79589081e-01 9.68464649e-01 1.36194584e-01
  3.88571958e-01 2.29623872e+00 2.65722052e+00 7.04718509e-02
  3.03228326e-01 1.59848617e-01 5.38671938e-01 9.00057075e-01
  1.61503939e-02 1.91366708e+00 4.60174619e-02 4.92194704e+00
  2.54220100e-01 7.64731345e-01 9.10526791e-01 3.90931868e-01
  2.12115349e-01 4.03814773e-01 3.03638562e-01 1.18514029e+00
  1.38172079e+00 1.72032925e-01 1.99029765e+00 3.68373762e+00
  6.65975136e-01 4.47210838e-01]]

### Pivot Table

In [21]:
#Determine pivot table
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                       "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [22]:
df.head(9)

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [23]:
###################################想办法生成以下表格，行为A、B，列为C###################################
table = pivot_table(df, values='D', index=['A', 'B'],
                  columns=['C'], aggfunc=np.sum)

###################################想办法生成以下表格，行为A、B，列为C###################################
table

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

### Merging dataframes

In [24]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])
    

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                       index=[4, 5, 6, 7])
    

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                       index=[8, 9, 10, 11])
    
###################################将df1,df2,df3按行拼接到一起，并赋给result###################################
frames = [df1, df2, df3]

result = pd.concat(frames)

###################################将df1,df2,df3按行拼接到一起，并赋给result####################################

print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11